//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sello.Localization.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource()
        {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sello.Localization.Shared.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Exists.
        /// </summary>
        public static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Used Coupon With Same Customer.
        /// </summary>
        public static string AlreadyUsedCouponWithSameCustomer {
            get {
                return ResourceManager.GetString("AlreadyUsedCouponWithSameCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon Code Already Exist.
        /// </summary>
        public static string CouponCodeAlreadyExist {
            get {
                return ResourceManager.GetString("CouponCodeAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account NotAllowed BecauseOf EntryDetails.
        /// </summary>
        public static string DeleteAccountNotAllowedBecauseOfEntryDetails {
            get {
                return ResourceManager.GetString("DeleteAccountNotAllowedBecauseOfEntryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Bank NotAllowed BecauseOF Stores.
        /// </summary>
        public static string DeleteBankNotAllowedBecauseOFStores {
            get {
                return ResourceManager.GetString("DeleteBankNotAllowedBecauseOFStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Category Not Allowed BecauseOF Items.
        /// </summary>
        public static string DeleteCategoryNotAllowedBecauseOFItems {
            get {
                return ResourceManager.GetString("DeleteCategoryNotAllowedBecauseOFItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete CostCenter NotAllowed BecauseOf Accounts.
        /// </summary>
        public static string DeleteCostCenterNotAllowedBecauseOfAccounts {
            get {
                return ResourceManager.GetString("DeleteCostCenterNotAllowedBecauseOfAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Customer NotAllowed BecauseOF StoreDocuments.
        /// </summary>
        public static string DeleteCustomerNotAllowedBecauseOFStoreDocuments {
            get {
                return ResourceManager.GetString("DeleteCustomerNotAllowedBecauseOFStoreDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Department NotAllowed BecauseOf Employees.
        /// </summary>
        public static string DeleteDepartmentNotAllowedBecauseOfEmployees {
            get {
                return ResourceManager.GetString("DeleteDepartmentNotAllowedBecauseOfEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Employee NotAllowed BecauseOF Sales.
        /// </summary>
        public static string DeleteEmployeeNotAllowedBecauseOFSales {
            get {
                return ResourceManager.GetString("DeleteEmployeeNotAllowedBecauseOFSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Employee NotAllowed BecauseOF Stores.
        /// </summary>
        public static string DeleteEmployeeNotAllowedBecauseOFStores {
            get {
                return ResourceManager.GetString("DeleteEmployeeNotAllowedBecauseOFStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete FiscalYear NotAllowed BecauseOf Entries.
        /// </summary>
        public static string DeleteFiscalYearNotAllowedBecauseOfEntries {
            get {
                return ResourceManager.GetString("DeleteFiscalYearNotAllowedBecauseOfEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Item Not Allowed Because OF BuffetPreparationItems.
        /// </summary>
        public static string DeleteItemNotAllowedBecauseOFBuffetPreparationItems {
            get {
                return ResourceManager.GetString("DeleteItemNotAllowedBecauseOFBuffetPreparationItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Item Not Allowed Because OF Card Size Items.
        /// </summary>
        public static string DeleteItemNotAllowedBecauseOFCardSizeItems {
            get {
                return ResourceManager.GetString("DeleteItemNotAllowedBecauseOFCardSizeItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Item Not Allowed Because OF Store Request Details.
        /// </summary>
        public static string DeleteItemNotAllowedBecauseOFStoreRequestDetails {
            get {
                return ResourceManager.GetString("DeleteItemNotAllowedBecauseOFStoreRequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Job NotAllowed BecauseOf Employees.
        /// </summary>
        public static string DeleteJobNotAllowedBecauseOfEmployees {
            get {
                return ResourceManager.GetString("DeleteJobNotAllowedBecauseOfEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Store Not Allowed BecauseOf ItemTransactions.
        /// </summary>
        public static string DeleteStoreNotAllowedBecauseOfItemTransactions {
            get {
                return ResourceManager.GetString("DeleteStoreNotAllowedBecauseOfItemTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Store Not Allowed BecauseOf Kitchens.
        /// </summary>
        public static string DeleteStoreNotAllowedBecauseOfKitchens {
            get {
                return ResourceManager.GetString("DeleteStoreNotAllowedBecauseOfKitchens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Store Not Allowed BecauseOf StoreDocuments.
        /// </summary>
        public static string DeleteStoreNotAllowedBecauseOfStoreDocuments {
            get {
                return ResourceManager.GetString("DeleteStoreNotAllowedBecauseOfStoreDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Store Not Allowed BecauseOf StoreRequests.
        /// </summary>
        public static string DeleteStoreNotAllowedBecauseOfStoreRequests {
            get {
                return ResourceManager.GetString("DeleteStoreNotAllowedBecauseOfStoreRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Store Not Allowed BecauseOf Treasuries.
        /// </summary>
        public static string DeleteStoreNotAllowedBecauseOfTreasuries {
            get {
                return ResourceManager.GetString("DeleteStoreNotAllowedBecauseOfTreasuries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete StoreRequest Not Allowed BecauseOf StoreDocuments.
        /// </summary>
        public static string DeleteStoreRequestNotAllowedBecauseOfStoreDocuments {
            get {
                return ResourceManager.GetString("DeleteStoreRequestNotAllowedBecauseOfStoreDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Supplier NotAllowed BecauseOF StoreDocuments.
        /// </summary>
        public static string DeleteSupplierNotAllowedBecauseOFStoreDocuments {
            get {
                return ResourceManager.GetString("DeleteSupplierNotAllowedBecauseOFStoreDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Treasury NotAllowed BecauseOF CashDocuments.
        /// </summary>
        public static string DeleteTreasuryNotAllowedBecauseOFCashDocuments {
            get {
                return ResourceManager.GetString("DeleteTreasuryNotAllowedBecauseOFCashDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Treasury NotAllowed BecauseOF Store.
        /// </summary>
        public static string DeleteTreasuryNotAllowedBecauseOFStore {
            get {
                return ResourceManager.GetString("DeleteTreasuryNotAllowedBecauseOFStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Unit Not Allowed BecauseOf ItemTransactions.
        /// </summary>
        public static string DeleteUnitNotAllowedBecauseOfItemTransactions {
            get {
                return ResourceManager.GetString("DeleteUnitNotAllowedBecauseOfItemTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Unit NotAllowed BecauseOf ItemUnits.
        /// </summary>
        public static string DeleteUnitNotAllowedBecauseOfItemUnits {
            get {
                return ResourceManager.GetString("DeleteUnitNotAllowedBecauseOfItemUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occurred.
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t delete this node, bceause it has childs.
        /// </summary>
        public static string HasChilds {
            get {
                return ResourceManager.GetString("HasChilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid field length.
        /// </summary>
        public static string InValidFieldLength {
            get {
                return ResourceManager.GetString("InValidFieldLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string InValidUser {
            get {
                return ResourceManager.GetString("InValidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No CostCenter For This Branch.
        /// </summary>
        public static string NoCostCenterForThisBranch {
            get {
                return ResourceManager.GetString("NoCostCenterForThisBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error During Account Mapping..
        /// </summary>
        public static string NotMapped {
            get {
                return ResourceManager.GetString("NotMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order has been Paid.
        /// </summary>
        public static string OrderIsPaid {
            get {
                return ResourceManager.GetString("OrderIsPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Not Enough.
        /// </summary>
        public static string QuantityNotEnough {
            get {
                return ResourceManager.GetString("QuantityNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field Validation.
        /// </summary>
        public static string RequiredFieldValidation {
            get {
                return ResourceManager.GetString("RequiredFieldValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StoreDoument Delete Not Allowed BecauseOf StoreDocuments.
        /// </summary>
        public static string StoreDoumentDeleteNotAllowedBecauseOfStoreDocuments {
            get {
                return ResourceManager.GetString("StoreDoumentDeleteNotAllowedBecauseOfStoreDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created.
        /// </summary>
        public static string SuccessfullyCreated {
            get {
                return ResourceManager.GetString("SuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Deleted.
        /// </summary>
        public static string SuccessfullyDeleted {
            get {
                return ResourceManager.GetString("SuccessfullyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Posted.
        /// </summary>
        public static string SuccessfullyPosted {
            get {
                return ResourceManager.GetString("SuccessfullyPosted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Updated.
        /// </summary>
        public static string SuccessfullyUpdated {
            get {
                return ResourceManager.GetString("SuccessfullyUpdated", resourceCulture);
            }
        }
        public static string ValdationCodeSentToEmail
        {
            get
            {
                return ResourceManager.GetString("ValdationCodeSentToEmail", resourceCulture);
            }
        }

        public static string Welcome
        {
            get
            {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        public static string SuccessfullySended
        {
            get
            {
                return ResourceManager.GetString("SuccessfullySended", resourceCulture);
            }
        }
        public static string SuccessfullyRegistered
        {
            get
            {
                return ResourceManager.GetString("SuccessfullyRegistered", resourceCulture);
            }
        }
    }
}
